# Support Vector Regression

In [1]:
cd C:\Users\User\Desktop\Anindita Mitra\Dataset

C:\Users\User\Desktop\Anindita Mitra\Dataset


In [2]:
#Import all the library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# import Data set from the local directory
df = pd.read_csv("Position_Salaries.csv")

In [38]:
# to check the first 5 rows of the data
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [5]:
# Lets define the object X & Y 
x= df.iloc[:, 1:-1].values
y=df.iloc[:,-1].values

In [6]:
print(x)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [7]:
print (y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [8]:
# since y is in 1D array now we need to transform the same to 2D array
#shape : no of rows the new y has so to get that we will calcualte len(y), no of colums = 1
y = y.reshape(len(y), 1)

In [9]:
print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [39]:
# Splitting data into training and test set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x , y, test_size=0.3, random_state=0)

In [53]:
# Feature Scaling
#We need to seperately measure x & y since the values are different. if we combine it the result will not be proper
#as there is a lot of variance in data between x and y
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(x_train)
x_train = sc.fit_transform(x_train)
x_test =  sc.fit_transform(x_test)

In [54]:
# Training
from sklearn.svm import SVR
reg  =  SVR(kernel="linear")
reg.fit(x_train,y_train)
reg.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.7442085777600307

In [58]:
reg  =  SVR(kernel="poly")
reg.fit(x_train,y_train)
reg.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9241352319526501

In [56]:
reg  =  SVR(kernel="rbf")
reg.fit(x_train,y_train)
reg.score(x_test,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9844029530918887

In [74]:
#Prediction
y_pred = reg.predict(x_test)

In [75]:
y_pred

array([-0.66377736,  0.8351387 , -0.16413867])

In [77]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print('MSE = ', mse)
print('RMSE = ', rmse)

MSE =  0.036387821831962874
RMSE =  0.1907559221412611


In [78]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9241352319526501